kitchen:
  polygon_path: package://overworld/models/areas/area_test.obj
  z_min: 0
  z_max: 3.5
  hysteresis: 0.4

cylinder:
  center:
    x: 3.5
    y: 4.6
    z: 1.5
  half_height: 1.4
  radius: 1.2
  hysteresis: 0.2