adream_walls:
  orientation:
    z: 1.57

adream_floor:
  orientation:
    z: 1.57

#adream_window_h10_1:
#  orientation:
#    z: 1.57

#adream_window_h10_2:
#  orientation:
#    z: 1.57

#adream_window_h20_1:
#  orientation:
#    z: 1.57

#adream_window_h20_2:
#  orientation:
#    z: 1.57

#adream_window_h20_3:
#  orientation:
#    z: 1.57

adream_appartment:
  orientation:
    z: 1.57
