kitchen:
  pose:
    x: 6.5
    y: 5.6
    z: 1.75
  polygon_path: package://overworld/models/areas/area_test.obj
  half_height: 1.75
  hysteresis: 0.4

cylinder:
  pose:
    x: 3.5
    y: 4.6
    z: 1.5
  half_height: 1.4
  radius: 1.2
  hysteresis: 0.2